name: pangeo-ml
channels:
  - conda-forge
dependencies:
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - sparse
  # data science
  - anaconda::tensorflow=2.0.0
  - anaconda::tensorflow-probability=0.8.0
  - mlflow
